### ISSUE TITLE
feature request: add influx and Prometheus data so it’s compatible with what `docker-readsb-protobuf` provides

### ISSUE THREAD

**Issue by kx1t** [sdr-enthusiasts/docker-tar1090#109]
Add a Telegraf instance that provides data for Influx and Prometheus to ingest. Ideally, the fields and values should be compatible with what `docker-readsb-protobuf` already provides so the existing Grafana dashboards can be reused. 

For Prometheus, I already mapped http://xxx/metrics -> `/run/readsb/stats.prom` but the data available there is different and much less than what’s generated by docker-readsb-protobuf. Ideally, the additional data should just be added to `/run/readsb/stats.prom`

For Influx -- I have no idea how that works

Thanks!

**Comment by dirkhh** [comment]
Definitely interested to see this. Happy to help if I can.

**Comment by kx1t** [comment]
hey @mikenye , with the appearance of our [ultrafeeder](https://github.com/sdr-enthusiasts/docker-adsb-ultrafeeder) that combines tar1090 with the multifeeder's multiple MLAT clients and integrates an MLATHUB, it would be great if we could get this working so tar1090 (and ultrafeeder) would be able to integrate with Grafana dashboards.

I'd do it myself but I have very little knowledge about how to create this data stream. --thanks!
