### ISSUE TITLE
Add environment variable option for graphs1090 range units.

### ISSUE THREAD

**Issue by TheDevFreak** [sdr-enthusiasts/docker-tar1090#139]
At the moment it is not possible to configure the range for graphs1090 as seen here: https://github.com/wiedehopf/graphs1090/blob/master/default#L13

**Comment by kx1t** [comment]
Sorry -- didn't see this until now. Running the checks on your PR as we speak

**Comment by kx1t** [comment]
@TheDevFreak Can you take a look at the linter and build issues for the PR and resolve them? Thanks
