### ISSUE TITLE
readsb runing even if i feed tar1090 from another source

### ISSUE THREAD

**Issue by 73-de-LZ** [sdr-enthusiasts/docker-tar1090#147]
Is  it necessary readsb to start in the container if tar1090 getting data from an external source? If not, is it possible to add env var READSB_ENABLE for example.

Thanks!

**Comment by kx1t** [comment]
Readsb is used to collect data from any source, including RTLSDR devices and also other Beast / SBS / Raw / etc sources. It's also needed as a backend to tar1090 (website generation), etc. So no -- you can't switch it off.
