### ISSUE TITLE
timelapse1090 data not persisting

### ISSUE THREAD

**Issue by trenchcoatjedi** [sdr-enthusiasts/docker-tar1090#76]
Running the latest version of docker-tar1090 container. timelapse1090 data does not persist if the container needs to be stopped but heatmap data does. Docker must stop for 10 minutes each night so the server can complete a backup and update cycle. When docker restarts the container, the timelapse1090 data is wiped from the volume when it is restarted. I have tried multiple workarounds to solve this and am coming up empty including mapping the timelapse1090 volume to an external docker volume by adding the following to docker-compose.yml:

```
volumes:
  timelapse:
    external: 
      name: timelapse
```

Add the following to tar1090
```
    volumes:
      - timelapse:/var/timelapse1090
```

The container will use the external volume but will wipe the volume when it starts up. I have a cron script running that copies the chunk_XXX.gz files every hour and synchronizing the data back to the docker volume path after the sever reboots so I am not loosing data but it would be much more convenient if there were a TIMELAPSE1090_PERSIST flag where if set to true would not wipe the docker storage volume when the container is restarted.

Here is the tar1090 config

    tar1090:
    image: mikenye/tar1090:latest
    tty: true
    container_name: tar1090
    restart: always
    depends_on:
      - readsb
    environment:
      - UPDATE_TAR1090=false
      - TZ=${FEEDER_TZ}
      - BEASTHOST=readsb
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - TAR1090_DEFAULTCENTERLAT=${FEEDER_LAT}
      - TAR1090_DEFAULTCENTERLON=${FEEDER_LONG}
      - MLATHOST=mlathub
      - ENABLE_TIMELAPSE1090=true
      - TIMELAPSE1090_INTERVAL=1
      - TIMELAPSE1090_HISTORY=168
      - GZIP_LVL=1
      - TAR1090_FLIGHTAWARELINKS=true
      - TAR1090_PLANECOUNTINTITLE=true
    volumes:
      - timelapse:/var/timelapse1090
      - tar1090_heatmap:/var/globe_history
    ports:
      - 80:80
    tmpfs:
      - /run:exec,size=64M
      - /var/log

**Comment by mikenye** [comment]
Hi @trenchcoatjedi,

This is the behaviour of timelapse1090 itself.

When starting up, it performs some `rm` commands: https://github.com/wiedehopf/timelapse1090/blob/8eb023b878a2e80e5a22e4eb81bcc1194c08940d/timelapse1090.sh#L34

I'm not sure what the impact of disabling these `rm` commands would be.

I would suggest opening an issue on the wiedehopf/timelapse1090 repo and asking the question.

-Mike

**Comment by kx1t** [comment]
Cleaning up -- is it OK to close this issue?
It looks like the solution is not with the container, but with the underlying code and user was advised to open an issue there.

Thanks --kx1t
